// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/data-panel.html"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/tesseract/languages/eng.traineddata.gz"
    | "/tesseract/tesseract-core-lstm.wasm.js"
    | "/tesseract/tesseract-core-simd-lstm.wasm.js"
    | "/tesseract/tesseract-core-simd.wasm.js"
    | "/tesseract/tesseract-core.wasm.js"
    | "/tesseract/tesseract.min.js"
    | "/tesseract/worker.min.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
